---

ignition_json:
  ignition:
    version: "2.2.0"
  systemd:
    units:
    - name: haproxy.service
      enable: true
      contents: |
        [Unit]
        Description=HAProxy Podman Container
        After=network.target
        [Service]
        Type=simple
        TimeoutStartSec=5m
        ExecStartPre=-/usr/bin/podman rm "haproxy-service"
        ExecStart=/usr/bin/podman run --name haproxy-service -v /etc/haproxy:/usr/local/etc/haproxy:Z --net host docker.io/haproxy:latest
        ExecReload=-/usr/bin/podman stop "haproxy-service"
        ExecReload=-/usr/bin/podman rm "haproxy-service"
        ExecStop=-/usr/bin/podman stop "haproxy-service"
        Restart=always
        RestartSec=30
        [Install]
        WantedBy=multi-user.target

  storage:
    files:
    - filesystem: "root"
      path: "/etc/haproxy/haproxy.conf"
      mode: 420
      contents:
        source: "data:text/plain;charset=utf-8;{{ lookup('template', 'haproxy.conf.j2') | b64encode }}"
      user:
        name: "root"
    - filesystem: "root"
      path: "/etc/sysconfig/network-scripts/ifcfg-{{ iface }}"
      mode: 420
      contents:
        source: "data:,{{ lookup('template', 'ifcfg.j2') | urlencode() }}"
      user:
        name: "root"

