---
- name: Create Ignition Files
  copy:
    content: "{{ ignition | to_json }}"
    dest: "/var/lib/libvirt/images/{{ inventory_hostname }}.ign"
    owner: qemu
    group: qemu
  delegate_to: libvirt1
