---

- name: Get ignition
  set_fact:
    ignition_json: "{{ lookup('file', lookup('env', 'PWD') ~ '/assets/' ~ node_type ~ '.ign') | from_json }}"

- name: combine
  set_fact:
    systemd_units: "{{ ignition_json['systemd']['units'] | default([]) | union(ignition_updates['systemd']['units']) }}"
- set_fact:
    ignition_json: "{% set test = ignition_json.update({'systemd': {'units': systemd_units}}) %}{{ ignition_json }}"

- name: Create Ignition Files
  copy:
    content: "{{ ignition_json | to_json }}"
    dest: "/var/lib/libvirt/images/{{ inventory_hostname }}.ign"
    owner: qemu
    group: qemu
  delegate_to: libvirt1
