---

- name: Create OpenShift Install Assets
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    aws_region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
    cluster_id: "{{ lookup('env', 'OPT_CLUSTER_ID') }}"
    pull_secret_path: "{{ lookup('env', 'OPT_PULL_SECRET') }}"
    private_key_path: "{{ lookup('env', 'OPT_PRIVATE_KEY') }}"

  tasks:
  ## Create install-config.yaml
  - name: Retrieve pull secret
    slurp:
      src: "{{ pull_secret_path }}"
    register: pull_secret
    no_log: true

  - name: Ensure proper permissions on private key file
    file:
      path: "{{ private_key_path }}"
      mode: 0600

  - name: Create public key from private key file
    command: >
      ssh-keygen -f {{ private_key_path }} -y
    register: keygen_output

  ## install-config.yaml
  - name: Create install-config.yaml
    template:
      src: install-config.yaml.j2
      dest: assets/install-config.yaml
