---
#- name: Create DNS Entries
#  hosts: dns
#  gather_facts: false
#  tasks:
#  - import_role:
#      name: dnsmasq
#
- name: OpenShift Prereq and Configuration
  hosts: lb
  connection: local
  gather_facts: false
  tasks:
    #  - import_role:
    #      name: openshift_client
    #  - import_role:
    #      name: assets
  - import_role:
      name: lb
      #
      #- name: OpenShift installer
      #  hosts: masters:workers:bootstrap
      #  gather_facts: false
      #  tasks:
      #  - import_role:
      #      name: nodes
      #  - import_role:
      #      name: machines
      #
