---
- name: OpenShift Prereq and Configuration
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
  - import_role:
      name: openshift_client
  - import_role:
      name: assets

- name: OpenShift installer
  hosts: masters:workers:bootstrap
  gather_facts: false
  tasks:
  - import_role:
      name: nodes
  - import_role:
      name: machines

